# Generated by Django 5.2.8 on 2025-11-15 05:49

import django.core.validators-
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # phụ thuộc vào bảng User
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # CÁC THAO TÁC DATABASE
    operations = [
        migrations.CreateModel(
            name='Book', #tạo bảng Book(sách)
            fields=[ # tạo các cột trong bảng
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), #ID tự tăng, khóa chính
                ('name', models.CharField(max_length=200)), #tối đa 200 kí tự
                ('price', models.DecimalField(decimal_places=2, max_digits=10, 
                                              validators=[django.core.validators.MinValueValidator(0)])), # giá tiền không âm, lưu chính xác giá tiền
                ('image', models.ImageField(blank=True, null=True, upload_to='books/')), #Lưu trong thư mục media/books/; có thể để trống
                ('description', models.TextField(blank=True)),  #Mô tả sách, cho phép rỗng
                ('created_at', models.DateTimeField(auto_now_add=True)), #thời gian tạo sách tự động
                ('updated_at', models.DateTimeField(auto_now=True)), #thời gian cập nhật cuối
            ],
            options={
                'ordering': ['-created_at'], #Sách mới nhất lên trước
            },
        ),
        migrations.CreateModel(
            name='Grade', #tạo bảng Grade(lớp học)
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)), #Tên không trùng
                ('order', models.IntegerField(default=0)), #Thứ tự hiển thị
            ],
            options={
                'ordering': ['order', 'name'], #Thứ tự sắp sếp
            },
        ),
        migrations.CreateModel(
            name='Subject', #Tạo bảng Subject(môn học)
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'], #Sắp xếp A → Z
            },
        ),
        migrations.CreateModel(
            name='Comment', #Tạo bảng Comment(Bình luân người dùng)
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()), #Nội dung bình luận
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, 
                                           related_name='comments', to='books.book')), #Mỗi comment:thuộc 1 sách, nếu sách xóa → comment xóa
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', 
                                           to=settings.AUTH_USER_MODEL)), # Comment thuộc về user
            ],
            options={
                'ordering': ['-created_at'], 
            },
        ),
        #Thêm khóa ngoại vào Book
        migrations.AddField(  
            model_name='book',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, 
                                    related_name='books', to='books.grade'), # Mỗi sách thuộc 1 lớp học
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, 
                                    related_name='books', to='books.subject'), #Mỗi sách thuộc 1 môn học
        ),
        migrations.CreateModel(
            name='Rating', #Tạo bảng Rating(đánh giá sao cho sách)
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), 
                                                           django.core.validators.MaxValueValidator(5)])), #Chỉ cho phép 1–5 sao
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('book', 'user')}, #Mỗi user chỉ được đánh giá 1 lần / 1 sách
            },
        ),
    ]
